### ISSUE TITLE
[Suggestion]README

### ISSUE THREAD

**Issue by koji** [ITP-xStory/p5js-shaders#2]
Maybe you guys can mention to some cases which you think your targets try to use Shaders with p5js.

Ex
If you want to draw many 3D things on p5js sketch blah blah blah.

Or
Create a very simple sketch with shaders and without shaders then show fps?

**Comment by kcconch** [comment]
Thanks koji! right now they are just named from what I came up with while I was working on them, we will definitely rename to be more specific towards what targets might want to do with shaders, also the performance example would be great for the power of shaders section
