### ISSUE TITLE
"These two programs are run simultaneously for every single pixel on your canvas"

### ISSUE THREAD

**Issue by yousifalyousifi** [ITP-xStory/p5js-shaders#7]
**From:** https://itp-xstory.github.io/p5js-shaders/#/./docs/how-to-write-a-shader?id=the-shader-program-runs-like-this

It's a small error, but the vertex shader doesn't run for each pixel, only for each vertex.

**Source:**
https://en.wikibooks.org/wiki/GLSL_Programming/OpenGL_ES_2.0_Pipeline 
"Vertex Shader ... a small program in GLSL is applied to each vertex"

Thanks,
Yousif

**Comment by louiselessel** [comment]
Thank you for pointing out that it is still too ambiguously written. I have updated with more information on the difference between the two!
